services:
  backend:
    build: ./back
    container_name: backend_container
    ports:
      - "5000:5000"

  frontend:
    build: ./dash
    container_name: frontend_container
    ports:
      - "3001:3001"