import React, { useCallback, useEffect, useState } from "react";
import { Alert, Box, Button, Chip, MenuItem, Paper, Select, Snackbar, TextField, Typography } from "@mui/material";
import BusinessCenterIcon from "@mui/icons-material/BusinessCenter";
import PlayArrowIcon from "@mui/icons-material/PlayArrow";
import StopIcon from "@mui/icons-material/Stop";
import ContentCopyIcon from "@mui/icons-material/ContentCopy";
import server from "../environment";

const headers = () => ({ "Content-Type": "application/json", Authorization: `Bearer ${localStorage.getItem("token")}` });
const card = { borderRadius: "20px", border: "1px solid #f0f0f0", boxShadow: "0 2px 8px rgba(0,0,0,.04)", p: { xs: 2, sm: 3 } };
const title = { fontFamily: "'Playfair Display', serif", fontWeight: 800, color: "#1a1a2e" };
const field = { "& .MuiOutlinedInput-root": { borderRadius: "13px" } };

export default function ClientAgent() {
  const [data, setData] = useState(null); const [config, setConfig] = useState(null); const [note, setNote] = useState({}); const [snack, setSnack] = useState({ open: false, text: "", severity: "success" });
  const notify = (text, severity = "success") => setSnack({ open: true, text, severity });
  const load = useCallback(async () => { try { const res = await fetch(`${server}/api/client-agent/overview`, { headers: headers() }); const body = await res.json(); if (!res.ok) throw new Error(body.error || "Could not load Client Agent."); setData(body); setConfig(body.config); } catch (e) { notify(e.message, "error"); } }, []);
  useEffect(() => { load(); }, [load]);
  const request = async (path, method = "POST", body) => { const res = await fetch(`${server}/api/client-agent${path}`, { method, headers: headers(), body: body === undefined ? undefined : JSON.stringify(body) }); const result = await res.json(); if (!res.ok) throw new Error(result.error || "Request failed."); return result; };
  const act = async (fn, success) => { try { await fn(); notify(success); await load(); } catch (e) { notify(e.message, "error"); } };
  if (!data || !config) return <Box sx={{ p: 4 }}>Loading AI Client Agent…</Box>;
  const set = (key, value) => setConfig((old) => ({ ...old, [key]: value }));
  const enquiryLink = `${window.location.origin}${data.enquiryPath}`;
  return <Box sx={{ maxWidth: 1200, mx: "auto", pb: 4 }}>
    <Box sx={{ mb: 3 }}><Typography sx={{ fontFamily: "'DM Sans', sans-serif", fontSize: 11, fontWeight: 800, color: "#999", letterSpacing: "1.5px" }}>APPROVAL-GATED · ADMIN ONLY</Typography><Typography sx={{ ...title, fontSize: { xs: 26, sm: 32 } }}>AI Client Agent</Typography><Typography sx={{ fontFamily: "'DM Sans', sans-serif", color: "#777", mt: .5 }}>Collects authorised leads and project enquiries. It never accepts work, commits to a client, sends delivery, or requests payment without your approval.</Typography></Box>
    <Paper sx={{ ...card, mb: 3, borderColor: config.running ? "#1a1a2e" : "#f0f0f0" }}><Box sx={{ display: "flex", gap: 1, alignItems: "center", mb: 2 }}><BusinessCenterIcon sx={{ color: "#1a1a2e" }}/><Typography sx={{ ...title, fontSize: 19 }}>Client-Finding Strategy <Chip size="small" label={config.running ? "Running" : "Stopped"} sx={{ ml: 1 }}/></Typography></Box><Box sx={{ display: "grid", gridTemplateColumns: { xs: "1fr", md: "1fr 1fr" }, gap: 2 }}><TextField fullWidth label="Client types (comma-separated)" value={(config.clientTypes || []).join(", ")} onChange={(e) => set("clientTypes", e.target.value.split(",").map((v) => v.trim()).filter(Boolean))} sx={field}/><TextField fullWidth label="Services offered (comma-separated)" value={(config.services || []).join(", ")} onChange={(e) => set("services", e.target.value.split(",").map((v) => v.trim()).filter(Boolean))} sx={field}/><TextField fullWidth type="number" label="Minimum budget (₹)" value={config.minimumBudget} onChange={(e) => set("minimumBudget", e.target.value)} sx={field}/><TextField fullWidth label="Business/studio name" value={config.businessName} onChange={(e) => set("businessName", e.target.value)} sx={field}/><TextField fullWidth label="Contact email" value={config.contactEmail} onChange={(e) => set("contactEmail", e.target.value)} sx={field}/><TextField fullWidth label="Enquiry link slug" value={config.enquirySlug} onChange={(e) => set("enquirySlug", e.target.value)} sx={field}/></Box><Box sx={{ display: "flex", gap: 1, mt: 2, flexWrap: "wrap" }}><Button variant="outlined" onClick={() => act(() => request("/config", "PUT", config), "Client Agent settings saved.")} sx={{ borderRadius: "12px", textTransform: "none" }}>Save strategy</Button><Button variant="contained" startIcon={config.running ? <StopIcon/> : <PlayArrowIcon/>} onClick={() => act(() => request(config.running ? "/stop" : "/start"), config.running ? "Agent stopped." : "Agent started. It will read only configured authorised sources.")} sx={{ borderRadius: "12px", textTransform: "none", bgcolor: "#1a1a2e" }}>{config.running ? "Stop client agent" : "Start freelancing"}</Button><Button startIcon={<ContentCopyIcon/>} onClick={() => { navigator.clipboard.writeText(enquiryLink); notify("Client enquiry link copied."); }} sx={{ textTransform: "none" }}>Copy enquiry link</Button></Box><Alert severity="info" sx={{ mt: 2, borderRadius: "12px" }}>Share this only with trusted prospects: {enquiryLink}. Marketplace/API lead discovery requires an authorised source URL configured in the backend environment.</Alert></Paper>
    <Paper sx={{ ...card, mb: 3 }}><Typography sx={{ ...title, fontSize: 19, mb: 1 }}>Client Leads</Typography>{data.leads.length === 0 ? <Typography sx={{ color: "#888" }}>No enquiries yet. Use the shareable enquiry link or connect an authorised lead source.</Typography> : data.leads.map((lead) => <Box key={lead._id} sx={{ borderTop: "1px solid #eee", py: 1.5 }}><Typography sx={{ fontWeight: 800 }}>{lead.businessName} <Chip label={`${lead.fitScore}/100 fit`} size="small" sx={{ ml: 1 }}/><Chip label={lead.status} size="small" sx={{ ml: 1 }}/></Typography><Typography sx={{ fontSize: 13, color: "#666", mt: .5 }}>{lead.requirement}</Typography><Typography sx={{ fontSize: 12, color: "#888", mt: .5 }}>{lead.analysis}</Typography><Box sx={{ display: "flex", gap: 1, flexWrap: "wrap", mt: 1 }}><Button size="small" onClick={() => act(() => request(`/leads/${lead._id}`, "PATCH", { status: "approved" }), "Lead approved for proposal preparation.")}>Review lead</Button><Button size="small" onClick={() => { const amount = window.prompt("Proposed amount in ₹"); const scope = window.prompt("Exact approved scope"); if (amount && scope) act(() => request(`/leads/${lead._id}/propose`, "POST", { title: `${lead.businessName} project`, scope, proposedAmount: amount }), "Project proposal created for admin approval."); }}>Create proposal</Button><Button size="small" color="inherit" onClick={() => act(() => request(`/leads/${lead._id}`, "PATCH", { status: "declined" }), "Lead declined.")}>Decline</Button></Box></Box>)}</Paper>
    <Paper sx={{ ...card, mb: 3 }}><Typography sx={{ ...title, fontSize: 19, mb: 1 }}>Projects & Approval Gates</Typography>{data.projects.length === 0 ? <Typography sx={{ color: "#888" }}>Approved proposals will appear here.</Typography> : data.projects.map((p) => <Box key={p._id} sx={{ borderTop: "1px solid #eee", py: 1.5 }}><Typography sx={{ fontWeight: 800 }}>{p.title} <Chip size="small" label={p.status} sx={{ ml: 1 }}/></Typography><Typography sx={{ fontSize: 13, color: "#666" }}>₹{p.proposedAmount} · {p.scope}</Typography><Box sx={{ display: "flex", gap: 1, flexWrap: "wrap", mt: 1 }}><Button size="small" onClick={() => navigator.clipboard.writeText(p.codexTask || "")}>Copy Codex task</Button>{p.status === "pending_admin_approval" && <Button size="small" onClick={() => act(() => request(`/projects/${p._id}/approve`, "PATCH", { decision: "approved" }), "Project approved; development brief is ready.")}>Approve work</Button>}{p.status === "in_progress" && <Button size="small" onClick={() => { const deliveryUrl = window.prompt("Delivery URL"); const testSummary = window.prompt("Test summary"); if (deliveryUrl) act(() => request(`/projects/${p._id}/delivery`, "PATCH", { deliveryUrl, testSummary }), "Sent to admin delivery review."); }}>Submit delivery review</Button>}{p.status === "awaiting_delivery_review" && <Button size="small" onClick={() => act(() => request(`/projects/${p._id}/delivery-review`, "PATCH", { decision: "approved" }), "Delivery approved. Payment can now be requested.")}>Approve delivery</Button>}{p.status === "delivery_approved" && <Button size="small" onClick={() => act(() => request(`/projects/${p._id}/request-payment`), "Secure Razorpay payment link created.")}>Create payment link</Button>}{p.paymentLink && <Button size="small" onClick={() => { navigator.clipboard.writeText(p.paymentLink); notify("Payment link copied."); }}>Copy payment link</Button>}</Box></Box>)}</Paper>
    <Paper sx={card}><Typography sx={{ ...title, fontSize: 19 }}>Audit Feed</Typography>{data.activities.slice(0, 10).map((a) => <Typography key={a._id} sx={{ borderTop: "1px solid #eee", py: 1, fontSize: 13 }}>{a.message} <Box component="span" sx={{ color: "#999" }}>· {new Date(a.createdAt).toLocaleString()}</Box></Typography>)}</Paper>
    <Snackbar open={snack.open} autoHideDuration={5000} onClose={() => setSnack((v) => ({ ...v, open: false }))}><Alert severity={snack.severity}>{snack.text}</Alert></Snackbar>
  </Box>;
}
