import React, { useEffect, useState } from "react";
import { Alert, Box, Button, Paper, Typography } from "@mui/material";
import { useParams } from "react-router-dom";
import server from "../environment";
function loadRazorpay() { return new Promise((resolve, reject) => { if (window.Razorpay) return resolve(); const script = document.createElement("script"); script.src = "https://checkout.razorpay.com/v1/checkout.js"; script.onload = resolve; script.onerror = reject; document.body.appendChild(script); }); }
export default function ProjectPayment() {
  const { code } = useParams(); const [project, setProject] = useState(null); const [message, setMessage] = useState("");
  const load = async () => { try { const res = await fetch(`${server}/api/client-agent/public/payment/${code}`); const body = await res.json(); if (!res.ok) throw new Error("Payment link is unavailable."); setProject(body); } catch (e) { setMessage(e.message); } };
  useEffect(() => { load(); }, [code]);
  const pay = async () => { try { await loadRazorpay(); const res = await fetch(`${server}/api/client-agent/public/payment/${code}/create-order`, { method: "POST" }); const order = await res.json(); if (!res.ok) throw new Error(order.error); new window.Razorpay({ key: order.key, amount: order.amount, currency: order.currency, name: "Project Studio", description: order.title, order_id: order.id, handler: async (response) => { const verify = await fetch(`${server}/api/client-agent/public/payment/${code}/verify`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(response) }); const done = await verify.json(); if (!verify.ok) return setMessage(done.error); setMessage(done.message); if (done.deliveryUrl) window.location.href = done.deliveryUrl; } }).open(); } catch (e) { setMessage(e.message || "Could not open secure checkout."); } };
  return <Box sx={{ minHeight: "100vh", background: "#fafafa", display: "grid", placeItems: "center", p: 2 }}><Paper sx={{ width: "100%", maxWidth: 550, p: 4, borderRadius: "22px" }}><Typography sx={{ fontFamily: "'Playfair Display', serif", fontWeight: 800, fontSize: 30, color: "#1a1a2e" }}>Secure Project Payment</Typography>{message && <Alert sx={{ mt: 2 }} severity={message.includes("verified") ? "success" : "error"}>{message}</Alert>}{project && <><Typography sx={{ mt: 2, fontWeight: 800 }}>{project.title}</Typography><Typography sx={{ color: "#666", mt: .5 }}>Amount: ₹{project.amount}</Typography><Button onClick={pay} disabled={project.status !== "payment_requested"} variant="contained" sx={{ mt: 3, borderRadius: "12px", bgcolor: "#1a1a2e", textTransform: "none" }}>Pay securely with Razorpay</Button></>}</Paper></Box>;
}
