import React, { useEffect, useState } from "react";
import { Alert, Box, Button, Paper, TextField, Typography } from "@mui/material";
import { useParams } from "react-router-dom";
import server from "../environment";
const field = { "& .MuiOutlinedInput-root": { borderRadius: "13px" } };
export default function ProjectEnquiry() {
  const { slug } = useParams(); const [info, setInfo] = useState(null); const [form, setForm] = useState({ businessName: "", contactName: "", email: "", phone: "", website: "", clientType: "", requirement: "", budget: "", deadline: "" }); const [message, setMessage] = useState("");
  useEffect(() => { fetch(`${server}/api/client-agent/public/enquiry/${slug}`).then(async (res) => { if (!res.ok) throw new Error(); return res.json(); }).then(setInfo).catch(() => setMessage("This project enquiry link is unavailable.")); }, [slug]);
  const set = (key, value) => setForm((old) => ({ ...old, [key]: value }));
  const submit = async (e) => { e.preventDefault(); try { const res = await fetch(`${server}/api/client-agent/public/enquiry/${slug}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const body = await res.json(); if (!res.ok) throw new Error(body.error); setMessage(body.message); } catch (error) { setMessage(error.message || "Could not send the enquiry."); } };
  return <Box sx={{ minHeight: "100vh", p: { xs: 2, md: 6 }, background: "#fafafa", display: "grid", placeItems: "center" }}><Paper component="form" onSubmit={submit} sx={{ width: "100%", maxWidth: 760, p: { xs: 2.5, sm: 4 }, borderRadius: "22px" }}><Typography sx={{ fontFamily: "'Playfair Display', serif", fontSize: 32, fontWeight: 800, color: "#1a1a2e" }}>{info?.businessName || "Project Studio"}</Typography><Typography sx={{ color: "#666", mt: 1, mb: 3 }}>Tell us about your project. An AI assistant will organise the details, then our admin reviews them before any commitment, work, timeline, or payment request.</Typography>{message && <Alert severity={message.includes("Thanks") ? "success" : "error"} sx={{ mb: 2 }}>{message}</Alert>}<Box sx={{ display: "grid", gridTemplateColumns: { xs: "1fr", sm: "1fr 1fr" }, gap: 2 }}><TextField required label="Business / organisation" value={form.businessName} onChange={(e) => set("businessName", e.target.value)} sx={field}/><TextField label="Your name" value={form.contactName} onChange={(e) => set("contactName", e.target.value)} sx={field}/><TextField label="Email" type="email" value={form.email} onChange={(e) => set("email", e.target.value)} sx={field}/><TextField label="Phone" value={form.phone} onChange={(e) => set("phone", e.target.value)} sx={field}/><TextField label="Website (optional)" value={form.website} onChange={(e) => set("website", e.target.value)} sx={field}/><TextField label="Project type" placeholder="Website, app, automation…" value={form.clientType} onChange={(e) => set("clientType", e.target.value)} sx={field}/><TextField required multiline minRows={5} label="Project requirements" value={form.requirement} onChange={(e) => set("requirement", e.target.value)} sx={{ ...field, gridColumn: { sm: "span 2" } }}/><TextField label="Approximate budget (₹)" type="number" value={form.budget} onChange={(e) => set("budget", e.target.value)} sx={field}/><TextField label="Preferred deadline" type="date" InputLabelProps={{ shrink: true }} value={form.deadline} onChange={(e) => set("deadline", e.target.value)} sx={field}/></Box><Button type="submit" variant="contained" sx={{ mt: 3, borderRadius: "12px", bgcolor: "#1a1a2e", textTransform: "none", fontWeight: 800 }}>Send for admin review</Button></Paper></Box>;
}
